package com.bitcomm;

public class ConstData {
	static String strName = "Monitoring Post PC Software";
	static String strDataTitel = "Gamma Ray Monitor";
	static String strTitle = "CURRENT DATA";
	static String strConfig = "Config";
	static String strTrend = "Trend Graph Data";
	static String strReport = "Report";
	static String strSpetru = "Spectrum Data";
	static String strClose = "Shut down";
	static String strStation = "Measurement Point";
	static String strDailyReprot = "Daily Report";
	static String strMonthReport = "Monthly Report";
	static String strPrint = "Print";
	static String strStartDate = "Designated Date";
	static String strStartTime = "Start Time";
	static String strEndDate = "Designated Period";
	static String strMax = "Maximum Value";
	static String strMin = "Minimum Value";
	static String strAvg = "Average Value";
	static String str3Sigma = "3σ Value";
	static String strTime = "Time";
	static String strDate = "Date";
	static String strSysSetup = "System Config";
	static String strStationNum = "Measure Point Number";
	static String strURL = "Server Name/IP";
	static String strNormal = "Normal";
	static String strCommErr = "Communication Error";
	static String strMonitorErr = "Measurement Device Trouble";
	static String strBattryLow = "Battery Exhaustion";
	static String strDetectorErr = "Detector Trouble";
	static String strGPSFail = "GPS Failure";
	static String strNoConnect = "Unconnection";
	static String strLoAlarm = "Alarm1";
	static String strHiAlarm = "Alarm2";
	static String strHihiAlarm = "Alarm3";
	static String strAbnoralData = "Non-complete Data";
	static String strDoesRate = "Dose Rate";
	static String strOffline = "OFF LINE";
	static String strMonitor = "Measurement Device";
	static String strCommuni = "Communication";
	static String strBattry = "Battery";
	static String strAlarm = "Alarm";
	static String strDetector = "Detector";
	static String strGPS = "GPS";
}
